name: Android CI (no-wrapper)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # >>> KLUCZOWE: doinstaluj platformę i build-tools, które pasują do compileSdk=35
      - name: Install Android SDK components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      # (opcjonalnie) upewnij się, że AAR jest w repo – w przeciwnym razie build i tak padnie
      - name: Verify AAR presence
        run: |
          ls -la app/libs || true
          if [ ! -f "app/libs/glyph-matrix-sdk-1.0.aar" ]; then
            echo "::error ::Missing SDK AAR at app/libs/glyph-matrix-sdk-1.0.aar"
            exit 1
          fi

      - name: Set up Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GlyphWolf-debug
          path: app/build/outputs/apk/debug/*.apk
