name: Android CI (no-wrapper)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Pobiera i udostępnia Gradle 8.7 (kompatybilny z AGP 8.6.x z naszego projektu)
      - name: Set up Gradle 8.7
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GlyphWolf-debug
          path: app/build/outputs/apk/debug/*.apk
