name: Unzip ZIP (safe)

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and unzip first ZIP
        run: |
          set -euo pipefail
          ZIP_FILE=$(git ls-files '*.zip' | head -n 1 || true)
          if [ -z "${ZIP_FILE}" ]; then
            echo "No .zip file found."
            exit 1
          fi
          echo "Found: ${ZIP_FILE}"
          DEST_DIR=$(dirname "${ZIP_FILE}")
          unzip -o "${ZIP_FILE}" -d "${DEST_DIR}"
          rm -f "${ZIP_FILE}"

      - name: Remove any workflow files from changes (security)
        run: |
          # Usuń ewentualne wypakowane pliki workflowów przed commit/push
          rm -rf .github/workflows || true

      - name: Commit unpacked files (excluding workflows)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          # dodatkowe zabezpieczenie — nie stage'uj nic w .github/workflows
          git reset .github/workflows || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-unzip archive(s) (workflows excluded)"
          git pull --rebase --autostash origin "${GITHUB_REF_NAME}" || true
          git push origin HEAD:"${GITHUB_REF_NAME}"
