name: Unzip any ZIP in repo

on:
  workflow_dispatch:      # run manually from Actions
  push:                   # also runs on any push (no path filters)

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and unzip archive(s)
        run: |
          set -euo pipefail
          # Find first .zip tracked in repo (you can adjust to unzip all zips if needed)
          ZIP_FILE=$(git ls-files '*.zip' | head -n 1 || true)
          if [ -z "${ZIP_FILE}" ]; then
            echo "No .zip file found in the repository."
            exit 1
          fi
          echo "Found ZIP: ${ZIP_FILE}"
          DEST_DIR=$(dirname "${ZIP_FILE}")
          echo "Unzipping into: ${DEST_DIR}"
          unzip -o "${ZIP_FILE}" -d "${DEST_DIR}"
          rm -f "${ZIP_FILE}"

      - name: Commit unpacked files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-unzip archive(s)"
          git pull --rebase --autostash origin "${GITHUB_REF_NAME}" || true
          git push origin HEAD:"${GITHUB_REF_NAME}"
