- name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -- ':!*.yml' ':!*.yaml' ':!/.github/workflows/*'
          git commit -m "Unzipped GlyphWolf_fixed.zip automatically" || echo "No changes to commit"
