name: Auto Unzip Project

on:
  push:
    branches:
      - main
      - master

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip GlyphWolf_fixed.zip
        run: |
          if [ -f "GlyphWolf_fixed.zip" ]; then
            echo "Found GlyphWolf_fixed.zip, extracting..."
            unzip -o GlyphWolf_fixed.zip -d .
            echo "✅ Extraction complete."
          else
            echo "❌ GlyphWolf_fixed.zip not found. Skipping."
          fi

      - name: Remove ZIP after extraction
        run: |
          if [ -f "GlyphWolf_fixed.zip" ]; then
            rm GlyphWolf_fixed.zip
            echo "🧹 ZIP file removed."
          fi

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped GlyphWolf_fixed.zip automatically" || echo "No changes to commit"

      - name: Push changes
        run: git push
