name: Unzip GlyphWolf.zip

on:
  workflow_dispatch:        # ręczne uruchomienie z karty Actions
  push:                     # auto, gdy zmieni się ZIP w podfolderze
    paths:
      - 'GlyphWolf/GlyphWolf.zip'

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Unzip if archive exists
        run: |
          set -e
          if [ -f "GlyphWolf/GlyphWolf.zip" ]; then
            unzip -o "GlyphWolf/GlyphWolf.zip" -d "GlyphWolf"
            rm -f "GlyphWolf/GlyphWolf.zip"
          else
            echo "Brak pliku GlyphWolf/GlyphWolf.zip — nic do rozpakowania."
          fi

      - name: Commit unpacked files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Auto-unzip GlyphWolf/GlyphWolf.zip"
          git pull --rebase --autostash origin "${GITHUB_REF_NAME}" || true
          git push origin HEAD:"${GITHUB_REF_NAME}"
